- hosts: ubuntuk
  become: true
  tasks: 
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/pod/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/pod/Service.yml
